export const BANK_SELECT = 'BANK_SELECT';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGINBUTTONCLICK = 'USER_LOGINBUTTONCLICK';
export const USER_LOGOUT = 'USER_LOGOUT';
export const STARTED_BUTTON_CLICK = 'STARTED_BUTTON_CLICK';
